# Generated by Django 2.1.5 on 2019-01-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('wx_openid', models.CharField(max_length=255)),
                ('wx_nickname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
