# Generated by Django 2.1.5 on 2019-04-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotTripSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(default='', max_length=30, null=True)),
                ('destination', models.CharField(default='', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.CharField(default='', max_length=2, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripDemoExamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.CharField(default='', help_text='1-找车 2-找人 3-全部', max_length=2, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(default='', max_length=30)),
                ('destination', models.CharField(default='', max_length=30)),
                ('leave_date', models.DateField(null=True)),
                ('leave_time', models.TimeField(null=True)),
                ('seats_count', models.PositiveSmallIntegerField(default=0, null=True)),
                ('people_count', models.PositiveSmallIntegerField(default=0, null=True)),
                ('vehicle', models.CharField(default='', max_length=20)),
                ('pc_type', models.CharField(default='1', help_text='1-找车 2-找人', max_length=2)),
                ('demo', models.TextField(default='', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(default='', max_length=20, null=True)),
                ('contact_phone', models.CharField(default='', max_length=30, null=True)),
                ('contact_wechat_account', models.CharField(default='', max_length=50, null=True)),
                ('contact_gender', models.CharField(default='', max_length=2, null=True)),
                ('contact_name', models.CharField(default='', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('isAgree', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=100)),
                ('wx_openid', models.CharField(default='', max_length=100, unique=True)),
                ('unionid', models.CharField(default='', max_length=100)),
                ('nickName', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=30)),
                ('avatarUrl', models.TextField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=2)),
                ('language', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('province', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=15)),
                ('session_key', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.User'),
        ),
        migrations.AddField(
            model_name='hottripsearch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.User'),
        ),
    ]
