# Generated by Django 2.1.5 on 2019-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_openid', models.CharField(default='', max_length=100)),
                ('departure', models.CharField(default='', max_length=30)),
                ('destination', models.CharField(default='', max_length=30)),
                ('leave_date', models.DateField(null=True)),
                ('leave_time', models.TimeField(null=True)),
                ('seats_count', models.PositiveSmallIntegerField(default=0)),
                ('people_count', models.PositiveSmallIntegerField(default=0)),
                ('pc_type', models.CharField(default='1', help_text='1-找车 2-找人', max_length=2)),
                ('demo', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(default='', max_length=20)),
                ('contact_phone', models.CharField(default='', max_length=30)),
                ('contact_wechat_account', models.CharField(default='', max_length=50)),
                ('contact_gender', models.CharField(default=1, max_length=1, null=True)),
                ('contact_name', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=100)),
                ('wx_openid', models.CharField(default='', max_length=100, unique=True)),
                ('unionid', models.CharField(default='', max_length=100)),
                ('nickName', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=30)),
                ('avatarUrl', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=2)),
                ('language', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('province', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=15)),
                ('session_key', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
