# Generated by Django 2.1.5 on 2019-02-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinfo',
            name='contact_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='contact_phone',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='contact_wechat_account',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='demo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='people_count',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='seats_count',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='status',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='wx_openid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.User', to_field='wx_openid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatarUrl',
            field=models.TextField(default='', max_length=200),
        ),
    ]
