# Generated by Django 2.1.5 on 2019-02-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20190221_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinfo',
            name='wx_openid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_openid', to='app_main.User', to_field='wx_openid'),
        ),
    ]
