# Generated by Django 2.1.5 on 2019-02-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_auto_20190221_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripinfo',
            name='wx_openid',
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.User'),
        ),
    ]
