# Generated by Django 2.1.5 on 2019-02-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_auto_20190221_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripinfo',
            old_name='uid',
            new_name='user',
        ),
    ]
