# Generated by Django 2.1.5 on 2019-02-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_auto_20190222_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotTripSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(default='', max_length=30)),
                ('destination', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
