# Generated by Django 2.1.5 on 2019-03-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_hottripsearch_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottripsearch',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tripinfo',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
